model_list:
  - model_name: "sonnet-4"
    litellm_params:
      model: "bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0"
      aws_region_name: us-west-2
  - model_name: "sonnet-4-anthropic"
    litellm_params:
      model: "anthropic/claude-sonnet-4-20250514"
      api_key: os.environ/ANTHROPIC_API_KEY

router_settings:
  fallbacks: [{ "sonnet-4": ["sonnet-4-anthropic"] }]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
